import os
from datetime import datetime
from fpdf import FPDF
from app.core.config import settings

class ReportGenerator:
    def __init__(self):
        # Mudamos para 'exports' para ficar mais profissional
        self.report_dir = "exports"
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)

    def generate_pdf(self, chat_history, analysis, client_name="Prospect"):
        """
        Gera um arquivo PDF profissional de Business Case.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"business_case_{client_name.lower()}_{timestamp}.pdf"
        filepath = os.path.join(self.report_dir, filename)

        pdf = FPDF()
        pdf.add_page()
        
        # --- CABEÇALHO ---
        pdf.set_fill_color(5, 150, 105) # Verde Esmeralda (Nexus Style)
        pdf.rect(0, 0, 210, 40, 'F')
        
        pdf.set_font("Arial", 'B', 16)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 10, f"EXECUTIVE SUMMARY: {settings.PROJECT_NAME}", ln=True, align='C')
        pdf.set_font("Arial", '', 10)
        pdf.cell(0, 10, f"Methodology: {settings.SERVICE_METHODOLOGY}", ln=True, align='C')
        
        pdf.ln(25) # Espaçamento
        
        # --- INFOS BÁSICAS ---
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(100, 10, f"Client: {client_name}")
        pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d/%m/%Y')}", ln=True, align='R')
        pdf.line(10, 55, 200, 55)
        pdf.ln(5)

        # --- SEÇÕES ---
        sections = [
            ("1. Operational Diagnosis (Weeks 1-2)", self._extract_section(chat_history, "diagnóstico")),
            ("2. Strategic Solution Design (Weeks 3-4)", self._extract_section(chat_history, "solução")),
        ]

        for title, content in sections:
            pdf.set_font("Arial", 'B', 12)
            pdf.set_text_color(6, 95, 70) # Verde Escuro
            pdf.cell(0, 10, title, ln=True)
            pdf.set_font("Arial", '', 11)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 7, content)
            pdf.ln(5)

        # --- INVESTIMENTO & ANÁLISE ---
        pdf.set_fill_color(240, 253, 244) # Fundo verdinho claro
        pdf.rect(10, pdf.get_y(), 190, 45, 'F')
        
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(6, 95, 70)
        pdf.cell(0, 10, "3. Business Case & Investment (Weeks 5-6)", ln=True)
        
        tier = settings.PRICING_TIERS['Enterprise'] if 'advanced' in analysis.lower() else settings.PRICING_TIERS['Standard']
        
        pdf.set_font("Arial", 'B', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, f"Selected Tier: {tier['label']}", ln=True)
        pdf.cell(0, 7, f"Value: ${tier['price']}", ln=True)
        
        pdf.set_font("Arial", 'I', 10)
        pdf.multi_cell(0, 7, f"Recommendation: {analysis}")
        
        pdf.ln(10)

        # --- RISCOS ---
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "4. Risk Matrix", ln=True)
        pdf.set_font("Arial", '', 10)
        risks = [
            "- Technical complexity: Mapped",
            "- Stakeholder alignment: Required",
            "- Integration readiness: To be validated in Phase 2"
        ]
        for risk in risks:
            pdf.cell(0, 6, risk, ln=True)

        # --- RODAPÉ ---
        pdf.set_y(-20)
        pdf.set_font("Arial", 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, f"Generated by {settings.PROJECT_NAME} - Proprietary Methodology.", align='C')

        pdf.output(filepath)
        return filename # Retornamos o nome para o download

    def _extract_section(self, history, keyword):
        relevant_messages = [m.content for m in history if keyword.lower() in m.content.lower() and m.role == "model"]
        if not relevant_messages:
            return "Details to be refined in the next consulting session based on identified bottlenecks."
        return relevant_messages[-1][:500]